### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by dev-onejun** [dev-onejun/tmp#3]
# Previous TODO list

Because I will manage the TODO list via Issue, I append the previous TODO list history in README.md

https://github.com/dev-onejun/dev-onejun.github.io/commits/master/README.md

**Comment by dev-onejun** [comment]
- [x] Hyperlink doesn’t work in inside of <iframe> tags

- https://dev-onejun.github.io/about
  - version 339158f

- the link, `my github`, is not working.

**Comment by dev-onejun** [comment]
- [x] delete Study/Github Study Repo Category
- [x] add Review/Event Category
  - [x] write about lablup conference and DDC 2023
 - [x] merge `Project` Category into `Review/Project`

**Comment by dev-onejun** [comment]
- [x] change `404.html` with more description
  - "The page you want may move to another category. Please use the search function in this blog"

**Comment by dev-onejun** [comment]
- [x] update `sitemap.xml` due to https://support.google.com/webmasters/answer/7440203#soft_404.
  - it reports automatically as Google by e-mail
  - https://github.com/dev-onejun/dev-onejun.github.io/commit/cd322f321062df5aac6c78f42a9eb765506a5d21

**Comment by dev-onejun** [comment]
- [x] xml error at `feed.xml`
  - xmlParseEntityRef: no name
  - related error at https://dev-onejun.github.io/study/server/2022/12/09/xml.html

https://github.com/dev-onejun/dev-onejun.github.io/commit/ee6ff361b50db0f5cff946445c505a67785fe10d
log is not appear because of the unlocking the conversation ...
